image: node:8.12.0
pipelines:
   branches:
      develop: # develop branch 
      - step: 
         deployment: test
         caches:
         - node
         script:
         - npm install
         - npm install -g firebase-tools 
         - npm test
         - npm rebuild node-sass
         - npm run build
         - ls -laR ./dist #recursively list directories
         - firebase deploy --token=$FIREBASE_TOKEN --project wevedo-76b03 --non-interactive
