image: node:9.11.2

pipelines:
  default:
    - step:
        name: Client: install modules and run build
        caches:
          - node
        script:
          - npm install
          - npm test
          - npm run build
        artifacts: # cache for next steps
          - dist/**
    - step:
        name: Client: Deploy to firebase
        script:
          - pipe: atlassian/firebase-deploy:0.3.0
            variables:
              FIREBASE_TOKEN: "1/Ys60ib1G1ylLihAeLDEnCajNmo2Pu5r0ofazuexr_DDj9QFhZT0JBelWlVjHTVa-"
              PROJECT_ID: "wevedo-76b03"
              DEBUG: 'true'
