version: 2
jobs:
  test:
    docker:
      - image: circleci/node:8.12.0
    steps:
      - checkout
      - restore_cache: 
          key: dependency-cache-{{ checksum "package.json" }}-{{ checksum "package-lock.json" }}
      - run:
          name: Setup dependencies
          command: npm install
      - save_cache: 
          key: dependency-cache-{{ checksum "package.json" }}-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run:
          name: Run tests and coverage
          command: npm test -- --coverage
      - run:
          name: Run eslint
          command: npm run lint:check 

workflows:
  version: 2
  build_test:
    jobs:
      - test
      