version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.12.0
    steps:
      - checkout
      - run:
          name: Setup dependencies
          command: npm install
      - run:
          name: Run eslint
          command: npm run lint:check 
      - run:
          name: Run tests and coverage
          command: npm test -- --coverage
