export const FETCH_LOGIN_REQUEST = 'FETCH_LOGIN_REQUEST';
export const FETCH_LOGIN_SUCCESS = 'FETCH_LOGIN_SUCCESS';
export const FETCH_LOGIN_FAILURE = 'FETCH_LOGIN_FAILURE';

export const FETCH_SIGNOUT_REQUEST = 'FETCH_SIGNOUT_REQUEST';
export const FETCH_SIGNOUT_SUCCESS = 'FETCH_SIGNOUT_SUCCESS';
export const FETCH_SIGNOUT_FAILURE = 'FETCH_SIGNOUT_FAILURE';
