export const EXTRACT_TOKEN_FROM_COOKIES = 'EXTRACT_TOKEN_FROM_COOKIES';

export const FETCH_SIGNUP_REQUEST = 'FETCH_SINGUP_REQUEST';
export const FETCH_SIGNUP_SUCCESS = 'FETCH_SINGUP_SUCCESS';
export const FETCH_SIGNUP_FAILURE = 'FETCH_SINGUP_FAILURE';

export const FETCH_LOGIN_REQUEST = 'FETCH_LOGIN_REQUEST';
export const FETCH_LOGIN_SUCCESS = 'FETCH_LOGIN_SUCCESS';
export const FETCH_LOGIN_FAILURE = 'FETCH_LOGIN_FAILURE';

export const FETCH_SIGNOUT_REQUEST = 'FETCH_SIGNOUT_REQUEST';
export const FETCH_SIGNOUT_SUCCESS = 'FETCH_SIGNOUT_SUCCESS';
export const FETCH_SIGNOUT_FAILURE = 'FETCH_SIGNOUT_FAILURE';

export const FETCH_EMAIL_STATUS_REQUEST = 'FETCH_EMAIL_STATUS_REQUEST';
export const FETCH_EMAIL_STATUS_SUCCESS = 'FETCH_EMAIL_STATUS_SUCCESS';
export const FETCH_EMAIL_STATUS_FAILURE = 'FETCH_EMAIL_STATUS_FAILURE';

export const FETCH_PHONE_STATUS_REQUEST = 'FETCH_PHONE_STATUS_REQUEST';
export const FETCH_PHONE_STATUS_SUCCESS = 'FETCH_PHONE_STATUS_SUCCESS';
export const FETCH_PHONE_STATUS_FAILURE = 'FETCH_PHONE_STATUS_FAILURE';

export const FETCH_USER_REQUEST = 'FETCH_USER_REQUEST';
export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS';
export const FETCH_USER_FAILURE = 'FETCH_USER_FAILURE';

export const UPDATE_USER_REQUEST = 'UPDATE_USER_REQUEST';
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';
export const UPDATE_USER_FAILURE = 'UPDATE_USER_FAILURE';

export const REMOVE_USER = 'REMOVE_USER';

export const FETCH_CATEGORIES_REQUEST = 'FETCH_CATEGORIES_REQUEST';
export const FETCH_CATEGORIES_SUCCESS = 'FETCH_CATEGORIES_SUCCESS';
export const FETCH_CATEGORIES_FAILURE = 'FETCH_CATEGORIES_FAILURE';

export const SET_DETECTED_COUNTRY = 'SET_DETECTED_COUNTRY';
export const SET_COUNTRY_SELECTED_BY_USER = 'SET_COUNTRY_SELECTED_BY_USER';
